[tools]
remodel = { github = "rojo-rbx/remodel", version = "0.9.1" }
rojo = { github = "rojo-rbx/rojo", version = "7.0.0" }
run-in-roblox = { github = "rojo-rbx/run-in-roblox", version = "0.3.0" }
selene = { github = "Kampfkarren/selene", version = "0.16.0" }
stylua = { github = "JohnnyMorganz/stylua", version = "0.12.3" }
darklua = { gitlab = "seaofvoices/darklua", version = "0.7.0" }
