[tools]
remodel = { github = "rojo-rbx/remodel", version = "0.9.1" }
rojo = { github = "rojo-rbx/rojo", version = "7.0.0" }
selene = { github = "Kampfkarren/selene", version = "0.15.0" }
stylua = { github = "JohnnyMorganz/stylua", version = "0.11.3" }
darklua = { gitlab = "seaofvoices/darklua", version = "0.7.0" }
