site_name: crosswalk
site_url: https://crosswalk.seaofvoices.ca/
repo_name: seaofvoices/crosswalk
repo_url: https://github.com/seaofvoices/crosswalk
edit_uri: ''

theme:
  name: material
  icon:
    logo: material/walk
    repo: fontawesome/brands/github
  favicon: images/walk.png
  palette:
    scheme: slate
    primary: orange

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.striphtml
  - pymdownx.details
  - pymdownx.superfences:
      preserve_tabs: true
  - pymdownx.tabbed:
      alternate_style: true
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

plugins:
  - search
  - minify:
      minify_html: true
  - awesome-pages:
      collapse_single_pages: true
