name: Release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'The version to release starting with `v`'
        required: true
        type: string

      release_ref:
        description: 'The branch, tag or SHA to checkout (default to latest)'
        default: ''
        type: string

permissions:
  contents: write

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest

    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

    steps:
      - uses: actions/checkout@v3

      - name: Create tag
        run: |
          git fetch --tags --no-recurse-submodules
          if [ ! $(git tag -l ${{ inputs.release_tag }}) ]; then
            git tag ${{ inputs.release_tag }}
            git push origin ${{ inputs.release_tag }}
          fi

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.release_tag }}
          name: ${{ inputs.release_tag }}
          draft: false

  build-assets:
    needs: create-release

    name: Build crosswalk assets
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build assets
        run: ./scripts/build-assets.sh

  upload-assets:
    needs:
      - create-release
      - build-assets
    name: Create release
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - artifact-name: server-loader.rbxm
            path: build/server-loader.rbxm
          - artifact-name: client-loader.rbxm
            path: build/client-loader.rbxm
          - artifact-name: server-main.rbxm
            path: build/server-main.rbxm
          - artifact-name: client-main.rbxm
            path: build/client-main.rbxm

          - artifact-name: server-loader-debug.rbxm
            path: build/debug/server-loader.rbxm
          - artifact-name: client-loader-debug.rbxm
            path: build/debug/client-loader.rbxm
          - artifact-name: server-main-debug.rbxm
            path: build/debug/server-main.rbxm
          - artifact-name: client-main-debug.rbxm
            path: build/debug/client-main.rbxm

    steps:
      - name: Upload asset
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact-name }}
          path: ${{ matrix.path }}

      - name: Add asset to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ${{ matrix.path }}
          asset_name: ${{ matrix.artifact-name }}
          asset_content_type: application/roblox

