name: Site

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-site:
    name: Build crosswalk site
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install python dependencies
        run: python -m pip install -r requirements.txt

      - uses: actions/setup-node@v3
        with:
          node-version: "latest"
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Build assets
        run: yarn run build-site

      - name: Build docs site
        run: |
          mkdir -p ./docs/releases
          rm -rf ./docs/releases/main
          cp -rf ./build ./docs/releases/main
          mkdocs build

      - name: Archive site
        uses: actions/upload-pages-artifact@v1
        with:
          path: site

  deploy:
    name: Deploy darklua site
    runs-on: ubuntu-latest
    needs: build-site
    if: github.ref == 'refs/heads/main'

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy site to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
