name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code-style:
    name: Verify code style
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify code format
        run: stylua --check src .lune test-place

  selene-check:
    name: Selene analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run selene checks
        run: selene src

  analyze:
    name: Luau analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run luau-lsp analysis
        run: ./scripts/analyze.sh
